# Generated by Django 4.2.6 on 2023-10-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.CharField(default='https://images.unsplash.com/photo-1642921131008-b13897b36d17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8JUU2JUI4JTg1JUU1JThEJThFJUU1JUE0JUE3JUU1JUFEJUE2fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60', max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_time', models.DateTimeField()),
                ('met', models.IntegerField(choices=[(0, 'Id'), (1, 'Phone'), (2, 'Email'), (3, 'Group'), (4, 'QRCode')])),
                ('mute1', models.BooleanField(default=False)),
                ('mute2', models.BooleanField(default=False)),
                ('frist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='users.user')),
                ('secend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='users.user')),
            ],
        ),
    ]
