# Generated by Django 4.2.6 on 2023-10-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='frist_user',
            new_name='first_user',
        ),
        migrations.AddField(
            model_name='relationship',
            name='state',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Passed'), (2, 'Deleted')], default=0),
        ),
    ]
